name: "Install llvmpipe and lavapipe"
description: "Installs software only Vulkan driver"
runs:
  using: "composite"
  steps:
    - name: Install Lavapipe
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update -y -qq
        sudo apt-get install -y mesa-vulkan-drivers vulkan-tools
        echo "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.x86_64.json" >> "$GITHUB_ENV"
