name: Checkout and setup rust with cache support
description: Bootstrap action to checkout the code, install the rust toolchain and retrieve the Rust dependency cache if any.

inputs:
  rust-toolchain:
    type: string
    description: Rust toolchain to install
    required: true
  cache-key:
    type: string
    description: The cache name as defined in the CI workflow matrix
    required: true
  linux-pre-cleanup:
    type: bool
    default: true
    description: Cleanup some unnecessary files from linux runners (to be used only with GitHub linux runners)

runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Free unnecessary installed files on GH linux image
      if: runner.os == 'Linux' && inputs.linux-pre-cleanup == true
      # see https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: install rust
      uses: dtolnay/rust-toolchain@master
      with:
        components: rustfmt, clippy
        toolchain: ${{ inputs.rust-toolchain }}
    - name: caching
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.cache-key }}
        prefix-key: v11-rust
        cache-on-failure: false
        cache-all-crates: true
