name: Install rust
description: Install the rust toolchain with optional cache support

inputs:
  apt-packages:
    type: string
    description: Space-separated list of apt packages to install on Linux runners. Leave empty to skip.
    required: false
    default: "build-essential"
  cache-key:
    type: string
    description: The cache name as defined in the CI workflow matrix
    required: true
  shared-key:
    type: string
    description: A shared key to use the cache across different jobs (overrides cache-key)
    default: ""
  workspaces:
    description: |
      The cargo workspaces and target directory configuration.
      Entries are separated by newlines and have the form `$workspace -> $target`.
      `$target` is relative to `$workspace` and defaults to `target` if omitted.
    required: false
    default: |
      . -> target
  enable-cache:
    type: bool
    default: true
    description: Whether to enable Rust dependency caching
    required: false
  rust-toolchain:
    type: string
    description: Rust toolchain to install
    default: stable

outputs:
  cache-hit:
    description: "A boolean value that indicates an exact match was found."
    value: ${{ steps.caching-step.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: free up space on GitHub runner
      if: runner.os == 'Linux' && runner.environment == 'github-hosted'
      run: |
        : Free up space on Linux Github runner image
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      shell: bash
    # --------------------------------------------------------------------------------
    - name: install dependencies
      if: runner.os == 'Linux' && inputs.apt-packages != ''
      run: |
        : Install dependencies
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt-packages }}
      shell: bash
    # --------------------------------------------------------------------------------
    - name: install rust
      uses: dtolnay/rust-toolchain@master
      with:
        components: rustfmt, clippy
        toolchain: ${{ inputs.rust-toolchain }}
    # --------------------------------------------------------------------------------
    - name: caching
      if: inputs.enable-cache == 'true'
      uses: Swatinem/rust-cache@v2
      id: caching-step
      with:
        key: ${{ inputs.cache-key }}
        shared-key: ${{ inputs.shared-key }}
        prefix-key: v11-rust
        cache-on-failure: false
        cache-all-crates: true
        workspaces: ${{ inputs.workspaces }}
    # --------------------------------------------------------------------------------
    - name: install xtask (unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        cargo install tracel-xtask-cli
    - name: install xtask (windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        cargo install tracel-xtask-cli
