# From wgpu repository:
# https://github.com/gfx-rs/wgpu/blob/trunk/.github/actions/install-mesa/action.yml
name: "Install Vulkan SDK"
description: "Install Vulkan SDK"
inputs:
  # Sourced from https://vulkan.lunarg.com/sdk/home#linux
  version:
    default: "1.4.328"
  full-version:
    default: "1.4.328.1"
runs:
  using: "composite"
  steps:
    - name: (Linux) Install Vulkan SDK
      if: runner.os == 'Linux'
      shell: bash
      env:
        VULKAN_SDK_VERSION: ${{ inputs.version }}
        VULKAN_FULL_SDK_VERSION: ${{ inputs.full-version }}
      run: |
        set -e

        curl -L --retry 5 https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_FULL_SDK_VERSION }}/linux/vulkansdk-linux-x86_64-${{ env.VULKAN_FULL_SDK_VERSION }}.tar.xz -o vulkan-sdk.tar.xz
        mkdir vulkan-sdk
        tar xpf vulkan-sdk.tar.xz -C vulkan-sdk

        mv ./vulkan-sdk/${{ env.VULKAN_FULL_SDK_VERSION }} $HOME/VulkanSDK

        echo "$HOME/VulkanSDK/x86_64/bin" >> "$GITHUB_PATH"
        echo "LD_LIBRARY_PATH=$HOME/VulkanSDK/x86_64/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" >> "$GITHUB_ENV"
        echo "VK_ADD_LAYER_PATH=$HOME/VulkanSDK/x86_64/share/vulkan/explicit_layer.d" >> "$GITHUB_ENV"

    - name: (Windows) Install Vulkan SDK
      if: runner.os == 'Windows'
      shell: bash
      env:
        VULKAN_SDK_VERSION: ${{ inputs.version }}
        VULKAN_FULL_SDK_VERSION: ${{ inputs.full-version }}
      run: |
        set -e

        curl.exe -L --retry 5 https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_FULL_SDK_VERSION }}/windows/vulkansdk-windows-X64-${{ env.VULKAN_FULL_SDK_VERSION }}.exe -o vulkan-sdk-installer.exe

        ./vulkan-sdk-installer.exe --accept-licenses --default-answer --confirm-command install

        echo "C:/VulkanSDK/${{ env.VULKAN_FULL_SDK_VERSION }}/Bin" >> "$GITHUB_PATH"

    - name: (Mac) Install Vulkan SDK
      if: runner.os == 'macOS'
      shell: bash
      env:
        VULKAN_SDK_VERSION: ${{ inputs.version }}
        VULKAN_FULL_SDK_VERSION: ${{ inputs.full-version }}
      run: |
        set -e

        curl -L --retry 5 https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_FULL_SDK_VERSION }}/mac/vulkansdk-macos-${{ env.VULKAN_FULL_SDK_VERSION }}.zip -o vulkan-sdk.zip
        unzip vulkan-sdk.zip -d vulkan-sdk

        ls -l vulkan-sdk
        sudo ./vulkan-sdk/vulkansdk-macOS-${{ env.VULKAN_FULL_SDK_VERSION }}.app/Contents/MacOS/vulkansdk-macOS-${{ env.VULKAN_FULL_SDK_VERSION }} --root "$HOME/VulkanSDK" --accept-licenses --default-answer --confirm-command install

        echo "$HOME/VulkanSDK/macOS/bin" >> "$GITHUB_PATH"
