name: Setup Linux Runner
description: Installs drivers and prepare the Linux runner

inputs:
  vulkan-sdk-version:
    type: string
    description: The version of the Vulkan SDK to install
    required: true
  mesa-version:
    type: string
    description: The version fo the MESA graphic library to install
    required: true
  mesa-ci-build-version:
    type: string
    description: The build version fo the MESA graphic library to install
    required: true
  cargo-package-to-clean:
    type: string
    default: ""
    description: The build version fo the MESA graphic library to install
    required: false
  linux-pre-cleanup:
    type: bool
    default: true
    description: Cleanup some unnecessary files from linux runners (to be used only with GitHub linux runners)

runs:
  using: "composite"
  steps:
    - name: Free disk space
      shell: bash
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        df -h
    - name: Free cargo packages
      if: inputs.cargo-package-to-clean != ''
      shell: bash
      run: |
        cargo clean --package ${{ inputs.cargo-package-to-clean }}
    - name: Free unnecessary installed files on GH linux image
      # if: inputs.runner-os == 'Linux' && inputs.linux-pre-cleanup == true
      # see https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    # --------------------------------------------------------------------------------
    - name: Install llvmpipe and lavapipe
      uses: tracel-ai/github-actions/setup-llvmpipe-lavapipe@v1
    # --------------------------------------------------------------------------------
    - name: Install Vulkan SDK
      # from wgpu repo: https://github.com/gfx-rs/wgpu/blob/trunk/.github/workflows/ci.yml
      shell: bash
      run: |
        set -e

        sudo apt-get update -y -qq

        # vulkan sdk
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${{ inputs.vulkan-sdk-version }}-jammy.list https://packages.lunarg.com/vulkan/${{ inputs.vulkan-sdk-version }}/lunarg-vulkan-${{ inputs.vulkan-sdk-version }}-jammy.list

        sudo apt-get update
        sudo apt install -y vulkan-sdk
    # --------------------------------------------------------------------------------
    - name: Install Mesa
      # from wgpu repo: https://github.com/gfx-rs/wgpu/blob/trunk/.github/workflows/ci.yml
      shell: bash
      run: |
        set -e

        curl -L --retry 5 https://github.com/gfx-rs/ci-build/releases/download/${{ inputs.mesa-ci-build-version}}/mesa-${{ inputs.mesa-version }}-linux-x86_64.tar.xz -o mesa.tar.xz
        mkdir mesa
        tar xpf mesa.tar.xz -C mesa

        # The ICD provided by the mesa build is hardcoded to the build environment.
        #
        # We write out our own ICD file to point to the mesa vulkan
        cat <<- EOF > icd.json
        {
          "ICD": {
              "api_version": "1.1.255",
              "library_path": "$PWD/mesa/lib/x86_64-linux-gnu/libvulkan_lvp.so"
          },
          "file_format_version": "1.0.0"
        }
        EOF

        echo "VK_DRIVER_FILES=$PWD/icd.json" >> "$GITHUB_ENV"
        echo "LD_LIBRARY_PATH=$PWD/mesa/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
        echo "LIBGL_DRIVERS_PATH=$PWD/mesa/lib/x86_64-linux-gnu/dri" >> "$GITHUB_ENV"
