name: Setup Linux Runner
description: Installs drivers and prepare the Linux runner

inputs:
  apt-packages:
    required: false
    type: string
    default: ""
  cargo-package-to-clean:
    type: string
    default: ""
    description: The build version fo the MESA graphic library to install
    required: false
  mesa-ci-build-version:
    type: string
    description: The build version fo the MESA graphic library to install
    required: true
  mesa-version:
    type: string
    description: The version fo the MESA graphic library to install
    required: true
  vulkan-sdk-version:
    type: string
    description: The version of the Vulkan SDK to install
    required: true

runs:
  using: "composite"
  steps:
    - name: Free disk space
      shell: bash
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        df -h
    - name: Free cargo packages
      if: inputs.cargo-package-to-clean != ''
      shell: bash
      run: |
        cargo clean --package ${{ inputs.cargo-package-to-clean }}
    # --------------------------------------------------------------------------------
    - name: Free unnecessary installed files on GH linux image
      if: runner.os == 'Linux' && runner.environment == 'github-hosted'
      # see https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    # --------------------------------------------------------------------------------
    - name: Install apt packages
      if: ${{ inputs.apt-packages != '' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt-packages }}
    # --------------------------------------------------------------------------------
    - name: Install llvmpipe and lavapipe
      uses: tracel-ai/github-actions/setup-llvmpipe-lavapipe@v4
    # --------------------------------------------------------------------------------
    - name: Install Vulkan SDK
      shell: bash
      run: |
        set -euo pipefail

        sudo apt-get update -y -qq

        # Create a dedicated keyring for LunarG (apt-key is removed on 24.04)
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://packages.lunarg.com/lunarg-signing-key-pub.asc \
          | sudo gpg --dearmor -o /etc/apt/keyrings/lunarg.gpg
        sudo chmod 0644 /etc/apt/keyrings/lunarg.gpg

        echo "deb [signed-by=/etc/apt/keyrings/lunarg.gpg] https://packages.lunarg.com/vulkan noble main" \
          | sudo tee /etc/apt/sources.list.d/lunarg-vulkan-noble.list > /dev/null

        sudo apt-get update -y -qq
        sudo apt-get install -y vulkan-sdk
