name: Setup Linux Runner
description: Installs drivers and prepare the Linux runner

inputs:
  vulkan-sdk-version:
    type: string
    description: The version of the Vulkan SDK to install
    required: true
  mesa-version:
    type: string
    description: The version fo the MESA graphic library to install
    required: true
  mesa-ci-build-version:
    type: string
    description: The build version fo the MESA graphic library to install
    required: true

runs:
  using: "composite"
  steps:
    - name: Free disk space
      shell: bash
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        df -h
        cargo clean --package burn-tch
    # --------------------------------------------------------------------------------
    - name: Install llvmpipe and lavapipe
      shell: bash
      run: |
        sudo apt-get update -y -qq
        for i in {1..5}; do
          sudo add-apt-repository ppa:kisak/kisak-mesa -y && break || sleep 5;
        done
        sudo apt-get update
        sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
    # --------------------------------------------------------------------------------
    - name: Install Vulkan SDK
      # from wgpu repo: https://github.com/gfx-rs/wgpu/blob/trunk/.github/workflows/ci.yml
      shell: bash
      run: |
        set -e

        sudo apt-get update -y -qq

        # vulkan sdk
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${{ inputs.vulkan-sdk-version }}-jammy.list https://packages.lunarg.com/vulkan/${{ inputs.vulkan-sdk-version }}/lunarg-vulkan-${{ inputs.vulkan-sdk-version }}-jammy.list

        sudo apt-get update
        sudo apt install -y vulkan-sdk
    # --------------------------------------------------------------------------------
    - name: Install Mesa
      # from wgpu repo: https://github.com/gfx-rs/wgpu/blob/trunk/.github/workflows/ci.yml
      shell: bash
      run: |
        set -e

        curl -L --retry 5 https://github.com/gfx-rs/ci-build/releases/download/${{ inputs.mesa-ci-build-version}}/mesa-${{ inputs.mesa-version }}-linux-x86_64.tar.xz -o mesa.tar.xz
        mkdir mesa
        tar xpf mesa.tar.xz -C mesa

        # The ICD provided by the mesa build is hardcoded to the build environment.
        #
        # We write out our own ICD file to point to the mesa vulkan
        cat <<- EOF > icd.json
        {
          "ICD": {
              "api_version": "1.1.255",
              "library_path": "$PWD/mesa/lib/x86_64-linux-gnu/libvulkan_lvp.so"
          },
          "file_format_version": "1.0.0"
        }
        EOF

        echo "VK_DRIVER_FILES=$PWD/icd.json" >> "$GITHUB_ENV"
        echo "LD_LIBRARY_PATH=$PWD/mesa/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
        echo "LIBGL_DRIVERS_PATH=$PWD/mesa/lib/x86_64-linux-gnu/dri" >> "$GITHUB_ENV"
