name: Setup Linux Runner
description: Installs drivers and prepare the Linux runner

inputs:
  apt-packages:
    required: false
    type: string
    default: ""
  cargo-package-to-clean:
    type: string
    default: ""
    description: The build version fo the MESA graphic library to install
    required: false

runs:
  using: "composite"
  steps:
    - name: Free disk space
      if: runner.os == 'Linux'
      shell: bash
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        df -h
    - name: Free cargo packages
      if: inputs.cargo-package-to-clean != ''
      shell: bash
      run: |
        cargo clean --package ${{ inputs.cargo-package-to-clean }}
    # --------------------------------------------------------------------------------
    - name: Free unnecessary installed files on GH linux image
      if: runner.os == 'Linux' && runner.environment == 'github-hosted'
      # see https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    # --------------------------------------------------------------------------------
    - name: Install apt packages
      if: runner.os == 'Linux' && ${{ inputs.apt-packages != '' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt-packages }}

