name: Setup Linux Runner
description: Installs drivers and prepare the Linux runner

inputs:
  apt-packages:
    required: false
    type: string
    default: ""
  cargo-package-to-clean:
    type: string
    default: ""
    description: The build version fo the MESA graphic library to install
    required: false
  mesa-ci-build-version:
    type: string
    description: The build version fo the MESA graphic library to install
    required: true
  mesa-version:
    type: string
    description: The version fo the MESA graphic library to install
    required: true
  vulkan-sdk-version:
    type: string
    description: The version of the Vulkan SDK to install
    default: "1.4.328.1"

runs:
  using: "composite"
  steps:
    - name: Free disk space
      shell: bash
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        df -h
    - name: Free cargo packages
      if: inputs.cargo-package-to-clean != ''
      shell: bash
      run: |
        cargo clean --package ${{ inputs.cargo-package-to-clean }}
    # --------------------------------------------------------------------------------
    - name: Free unnecessary installed files on GH linux image
      if: runner.os == 'Linux' && runner.environment == 'github-hosted'
      # see https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    # --------------------------------------------------------------------------------
    - name: Install apt packages
      if: ${{ inputs.apt-packages != '' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt-packages }}
    # --------------------------------------------------------------------------------
    - name: Install llvmpipe and lavapipe
      uses: tracel-ai/github-actions/setup-llvmpipe-lavapipe@v4
    # --------------------------------------------------------------------------------
    - name: Install Vulkan SDK
      shell: bash
      env:
        VULKAN_SDK_VERSION: ${{ inputs.version }}
        VULKAN_FULL_SDK_VERSION: ${{ inputs.full-version }}
      run: |
        set -e

        curl -L --retry 5 https://sdk.lunarg.com/sdk/download/${{ inputs.vulkan-sdk-version }}/linux/vulkansdk-linux-x86_64-${{ inputs.vulkan-sdk-version }}.tar.xz -o vulkan-sdk.tar.xz
        mkdir vulkan-sdk
        tar xpf vulkan-sdk.tar.xz -C vulkan-sdk

        mv ./vulkan-sdk/${{ inputs.vulkan-sdk-version }} $HOME/VulkanSDK

        echo "$HOME/VulkanSDK/x86_64/bin" >> "$GITHUB_PATH"
        echo "LD_LIBRARY_PATH=$HOME/VulkanSDK/x86_64/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" >> "$GITHUB_ENV"
        echo "VK_ADD_LAYER_PATH=$HOME/VulkanSDK/x86_64/share/vulkan/explicit_layer.d" >> "$GITHUB_ENV"

